//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookStore.Shared.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add book.
        /// </summary>
        public static string AddBook {
            get {
                return ResourceManager.GetString("AddBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add client.
        /// </summary>
        public static string AddClient {
            get {
                return ResourceManager.GetString("AddClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add comment.
        /// </summary>
        public static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to WishList.
        /// </summary>
        public static string AddToWishList {
            get {
                return ResourceManager.GetString("AddToWishList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item has already exist.
        /// </summary>
        public static string AlreadyExist {
            get {
                return ResourceManager.GetString("AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BirthDate.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book menu.
        /// </summary>
        public static string BookMenu {
            get {
                return ResourceManager.GetString("BookMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can`t logout.
        /// </summary>
        public static string CannotLogout {
            get {
                return ResourceManager.GetString("CannotLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose someone.
        /// </summary>
        public static string ChooseSomeone {
            get {
                return ResourceManager.GetString("ChooseSomeone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client menu.
        /// </summary>
        public static string ClientMenu {
            get {
                return ResourceManager.GetString("ClientMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client don`t exist.
        /// </summary>
        public static string ClientNotExist {
            get {
                return ResourceManager.GetString("ClientNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created success.
        /// </summary>
        public static string CreatedSuccess {
            get {
                return ResourceManager.GetString("CreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted success.
        /// </summary>
        public static string DeletedSuccess {
            get {
                return ResourceManager.GetString("DeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter first name.
        /// </summary>
        public static string EnterFirstName {
            get {
                return ResourceManager.GetString("EnterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an integer.
        /// </summary>
        public static string EnterInteger {
            get {
                return ResourceManager.GetString("EnterInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter last name.
        /// </summary>
        public static string EnterLastName {
            get {
                return ResourceManager.GetString("EnterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new author.
        /// </summary>
        public static string EnterNewAuthor {
            get {
                return ResourceManager.GetString("EnterNewAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new genre.
        /// </summary>
        public static string EnterNewGenre {
            get {
                return ResourceManager.GetString("EnterNewGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new name.
        /// </summary>
        public static string EnterNewName {
            get {
                return ResourceManager.GetString("EnterNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new price.
        /// </summary>
        public static string EnterNewPrice {
            get {
                return ResourceManager.GetString("EnterNewPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login success.
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout success.
        /// </summary>
        public static string LogoutSuccess {
            get {
                return ResourceManager.GetString("LogoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item don`t exist.
        /// </summary>
        public static string NotExist {
            get {
                return ResourceManager.GetString("NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotFound.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don`t have yet.
        /// </summary>
        public static string NotHave {
            get {
                return ResourceManager.GetString("NotHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program finished at.
        /// </summary>
        public static string ProgramFinished {
            get {
                return ResourceManager.GetString("ProgramFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program started at.
        /// </summary>
        public static string ProgramStarted {
            get {
                return ResourceManager.GetString("ProgramStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove book.
        /// </summary>
        public static string RemoveBook {
            get {
                return ResourceManager.GetString("RemoveBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove client.
        /// </summary>
        public static string RemoveClient {
            get {
                return ResourceManager.GetString("RemoveClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove comment.
        /// </summary>
        public static string RemoveComment {
            get {
                return ResourceManager.GetString("RemoveComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from WishList.
        /// </summary>
        public static string RemoveFromWishList {
            get {
                return ResourceManager.GetString("RemoveFromWishList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return back.
        /// </summary>
        public static string ReturnBack {
            get {
                return ResourceManager.GetString("ReturnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show books.
        /// </summary>
        public static string ShowBooks {
            get {
                return ResourceManager.GetString("ShowBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show clients.
        /// </summary>
        public static string ShowClients {
            get {
                return ResourceManager.GetString("ShowClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch language.
        /// </summary>
        public static string SwitchLanguage {
            get {
                return ResourceManager.GetString("SwitchLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update book.
        /// </summary>
        public static string UpdateBook {
            get {
                return ResourceManager.GetString("UpdateBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateClient.
        /// </summary>
        public static string UpdateClient {
            get {
                return ResourceManager.GetString("UpdateClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated success.
        /// </summary>
        public static string UpdatedSuccess {
            get {
                return ResourceManager.GetString("UpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users which wish.
        /// </summary>
        public static string UsersWhichWish {
            get {
                return ResourceManager.GetString("UsersWhichWish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WishList.
        /// </summary>
        public static string WishList {
            get {
                return ResourceManager.GetString("WishList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your choice.
        /// </summary>
        public static string YourChoice {
            get {
                return ResourceManager.GetString("YourChoice", resourceCulture);
            }
        }
    }
}
